name: Deploy Ghost Theme
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 'Deploy Ghost Theme'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
